### ISSUE TITLE
Velocity not work

### ISSUE THREAD

**Issue by Nukecraft5419** [Simonsator/Block-for-Party-and-Friends#3]
```
[19:15:44 ERROR]: Unable to load plugin plugins/Block-for-Party-and-Friends-1.0.5-RELEASE.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file Block-for-Party-and-Friends-1.0.5-RELEASE.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:154) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:64) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:345) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:227) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
```

**Comment by Simonsator** [comment]
This extension does not support velocity
